# Generated by Django 5.2.11 on 2026-05-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Deposit charged at booking time', max_digits=6),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='deposit_paid',
            field=models.BooleanField(default=False, help_text='True once deposit payment confirmed'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='deposit_session_id',
            field=models.CharField(blank=True, default='', help_text='Stripe session ID for deposit payment', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='late_cancel',
            field=models.BooleanField(default=False, help_text='True if cancelled within 2 hours of appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='shop_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When barber confirmed shop booking arrival', null=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='cashapp_tag',
            field=models.CharField(blank=True, default='', help_text='Cash App $cashtag for manual payouts', max_length=50),
        ),
        migrations.AlterField(
            model_name='barber',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barber',
            name='photo_data',
            field=models.TextField(blank=True, default='', help_text='Base64 encoded photo — persists across deploys'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='stripe_account_id',
            field=models.CharField(blank=True, default='', help_text='Stripe Connect Express account ID — set when barber connects Stripe', max_length=100),
        ),
        migrations.AlterField(
            model_name='barberavailability',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='barberclient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='barberserviceprice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='barbertimeoff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newsletterpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deposit_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Base $10. Increases $1.50 per strike after first.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Mobile number for SMS e.g. +16015551234', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='security_answer',
            field=models.CharField(blank=True, default='', help_text='Stored lowercase stripped for comparison', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='strike_count',
            field=models.PositiveIntegerField(default=0, help_text='Total no-shows + last-minute cancels'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Client accepted deposit & strike T&C'),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
