# Generated by Django 5.2.11 on 2026-05-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gallery_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='welcome_push_sent',
            field=models.BooleanField(default=False, help_text='Welcome push notification sent once on first login after signup'),
        ),
    ]
